export const BASE_URL_API = process.env.BASE_URL_API;
export const RESPONSE_STATUS = {
  SUCCESS: 200,
  NEED_ACTION: 300,
  UNAUTHORIZED: 401,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  ERROR: 500,
  ACCEPTED: 202,
};